import Page from '../../pages/page'
import AppointmentsPage from '../../pages/appointments'
import InstructionsPage from '../../pages/check-ins/instructions'
import DateFrequencyPage from '../../pages/check-ins/date-frequencey'
import { getCheckinUuid } from './imports'
import ContactPreferencePage from '../../pages/check-ins/contact-preference'
import PhotoOptionsPage from '../../pages/check-ins/photo-options'
import EditContactPreferencePage from '../../pages/check-ins/edit-contact-preference'
import ErrorPage from '../../pages/error'
import TakeAPhotoOptionsPage from '../../pages/check-ins/take-a-photo-options'
import UploadAPhotoPage from '../../pages/check-ins/upload-a-photo'
import PhotoRulesPage from '../../pages/check-ins/photo-rules'
import CheckYourAnswersPage from '../../pages/check-ins/check-your-answers'
import CheckinConfirmationPage from '../../pages/check-ins/confirmation.page'
import TakeAPhotoPage from '../../pages/check-ins/take-a-photo'
import { statusErrors } from '../../../server/properties'
import OverviewPage from '../../pages/overview'
import ManageCheckins from '../../pages/check-ins/manage-checkins'

const loadPage = () => {
  cy.task('resetMocks')
  cy.task('stubEnableESuperVision')
  cy.visit(`/case/X000001/appointments`)
}
context('Appointment check-ins', () => {
  it('Appointments page with online check-ins', () => {
    loadPage()
    const page = Page.verifyOnPage(AppointmentsPage)
    page.headerCrn().should('contain.text', 'X000001')
    page.headerName().should('contain.text', 'Caroline Wolff')
    cy.get('[data-qa="appointments-header-label"]').should('contain.text', 'Appointments')
    page.getElement('[data-qa="upcomingAppointments"]').find('h3').should('contain.text', 'Upcoming appointments')
    page
      .getElement('[data-qa="online-checkin-btn"]')
      .should('be.visible')
      .and('contain.text', 'Set up online check ins')
    page.getElement('[data-qa="online-checkin-btn"]').click()
    cy.url().should('contain', '/case/X000001/appointments/check-in/instructions')
    const instructionsPage = new InstructionsPage()
    instructionsPage.checkOnPage()
    instructionsPage.getElement('[data-qa="formAnchorLink"]').click()
    Page.verifyOnPage(AppointmentsPage)
  })

  it('check-in frequency page should fail with validation errors', () => {
    loadPage()
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.checkOnPage()
    dateFrequencyPage.getSubmitBtn().click()
    dateFrequencyPage.checkErrorSummaryBox([
      'Enter the date you would like the person to complete their first check in',
      'Select how often you would like the person to check in',
    ])

    getCheckinUuid().then(uuid => {
      dateFrequencyPage.getElement(`#esupervision-X000001-${uuid}-checkins-date-error`).should($error => {
        expect($error.text().trim()).to.include(
          'Enter the date you would like the person to complete their first check in',
        )
      })
      dateFrequencyPage.getElement(`#esupervision-X000001-${uuid}-checkins-interval-error`).should($error => {
        expect($error.text().trim()).to.include('Select how often you would like the person to check in')
      })
    })
  })

  it('should able to submit check-in frequency details', () => {
    loadPage()
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.checkOnPage()

    dateFrequencyPage.getDatePickerToggle().click()
    dateFrequencyPage.getNextDayButton().click()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    const contactPreferencePage = new ContactPreferencePage()
    contactPreferencePage.checkOnPage()
  })

  it('contact preference page should fail with validation errors', () => {
    loadPage()
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.getDatePickerToggle().click()
    dateFrequencyPage.getNextDayButton().click()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    const contactPreferencePage = new ContactPreferencePage()
    contactPreferencePage.checkOnPage()
    contactPreferencePage.getSubmitBtn().click()
    getCheckinUuid().then(uuid => {
      dateFrequencyPage.getElement(`#esupervision-X000001-${uuid}-checkins-preferredComs-error`).should($error => {
        expect($error.text().trim()).to.include('Select how the person wants us to send a link to the service')
      })
    })
  })

  it('should able to submit contact preference details', () => {
    loadPage()
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.getDatePickerToggle().click()
    dateFrequencyPage.getNextDayButton().click()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    const contactPreferencePage = new ContactPreferencePage()
    contactPreferencePage.checkOnPage()
    contactPreferencePage
      .getCheckInPreferredComs()
      .find('.govuk-radios__item')
      .eq(0)
      .find('.govuk-radios__input')
      .click()
    contactPreferencePage.getSubmitBtn().click()

    const photoOptionsPage = new PhotoOptionsPage()
    photoOptionsPage.checkOnPage()
  })

  it('should able to edit contact preference details', () => {
    loadPage()
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.getDatePickerToggle().click()
    dateFrequencyPage.getNextDayButton().click()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    const contactPreferencePage = new ContactPreferencePage()
    contactPreferencePage.checkOnPage()
    contactPreferencePage.getChangeLink().click()
    const editContactPreferencePage = new EditContactPreferencePage()
    editContactPreferencePage.checkOnPage()
    editContactPreferencePage.getSubmitBtn().click()
    contactPreferencePage.getElementData('updateBanner').should('contain.text', 'Contact details saved')
  })

  it('Should able to choose photo options', () => {
    loadPage()
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.getDatePickerToggle().click()
    dateFrequencyPage.getNextDayButton().click()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    const contactPreferencePage = new ContactPreferencePage()
    contactPreferencePage.checkOnPage()
    contactPreferencePage
      .getCheckInPreferredComs()
      .find('.govuk-radios__item')
      .eq(0)
      .find('.govuk-radios__input')
      .click()
    contactPreferencePage.getSubmitBtn().click()
    const takeAPhotoOptionsPage = new TakeAPhotoOptionsPage()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    takeAPhotoOptionsPage.getBackLink().click()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(1).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    const uploadablePhoto = new UploadAPhotoPage()
    uploadablePhoto.checkOnPage()
    uploadablePhoto.getBackLink().click()
    takeAPhotoOptionsPage.checkOnPage()
  })

  it('Should able to upload a pic and show rules page', () => {
    loadPage()
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.getDatePickerToggle().click()
    dateFrequencyPage.getNextDayButton().click()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    const contactPreferencePage = new ContactPreferencePage()
    contactPreferencePage.checkOnPage()
    contactPreferencePage
      .getCheckInPreferredComs()
      .find('.govuk-radios__item')
      .eq(0)
      .find('.govuk-radios__input')
      .click()
    contactPreferencePage.getSubmitBtn().click()
    const takeAPhotoOptionsPage = new TakeAPhotoOptionsPage()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    takeAPhotoOptionsPage.getBackLink().click()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(1).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    const uploadAPhoto = new UploadAPhotoPage()
    uploadAPhoto.checkOnPage()
    uploadAPhoto.uploadPhoto('person.jpg')
    uploadAPhoto.continueButton().click()
    const photoRules = new PhotoRulesPage()
    photoRules.checkOnPage()
    photoRules.getBackLink().click()
    uploadAPhoto.checkOnPage()
  })

  it('Should able to show cya and confirm page', () => {
    loadPage()
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.getDatePickerToggle().click()
    dateFrequencyPage.getNextDayButton().click()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    const contactPreferencePage = new ContactPreferencePage()
    contactPreferencePage.checkOnPage()
    contactPreferencePage
      .getCheckInPreferredComs()
      .find('.govuk-radios__item')
      .eq(0)
      .find('.govuk-radios__input')
      .click()
    contactPreferencePage.getSubmitBtn().click()
    const takeAPhotoOptionsPage = new TakeAPhotoOptionsPage()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    takeAPhotoOptionsPage.getBackLink().click()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(1).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    const uploadAPhoto = new UploadAPhotoPage()
    uploadAPhoto.checkOnPage()
    uploadAPhoto.uploadPhoto('person.jpg')
    uploadAPhoto.continueButton().click()
    const photoRules = new PhotoRulesPage()
    photoRules.checkOnPage()
    photoRules.getSubmitBtn().click()
    const checkYourAnswersPage = new CheckYourAnswersPage()
    checkYourAnswersPage.checkOnPage()
    checkYourAnswersPage.getSubmitBtn().click()
    const checkinConfirmationPage = new CheckinConfirmationPage()
    checkinConfirmationPage.checkOnPage()
  })

  it('Should able to take a photo and show cya and confirm page', () => {
    loadPage()
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.getDatePickerToggle().click()
    dateFrequencyPage.getNextDayButton().click()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    const contactPreferencePage = new ContactPreferencePage()
    contactPreferencePage.checkOnPage()
    contactPreferencePage
      .getCheckInPreferredComs()
      .find('.govuk-radios__item')
      .eq(0)
      .find('.govuk-radios__input')
      .click()
    contactPreferencePage.getSubmitBtn().click()
    const takeAPhotoOptionsPage = new TakeAPhotoOptionsPage()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    takeAPhotoOptionsPage.getBackLink().click()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    const takeAPhotoPage = new TakeAPhotoPage()
    takeAPhotoPage.checkOnPage()
    takeAPhotoPage.getSubmitBtn().click()
    const photoRules = new PhotoRulesPage()
    photoRules.checkOnPage()
    photoRules.getSubmitBtn().click()
    const checkYourAnswersPage = new CheckYourAnswersPage()
    checkYourAnswersPage.checkOnPage()
    checkYourAnswersPage.getSubmitBtn().click()
    const checkinConfirmationPage = new CheckinConfirmationPage()
    checkinConfirmationPage.checkOnPage()
  })

  it('Should able to change options from cya', () => {
    loadPage()
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.getDatePickerToggle().click()
    dateFrequencyPage.getNextDayButton().click()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    const contactPreferencePage = new ContactPreferencePage()
    contactPreferencePage.checkOnPage()
    contactPreferencePage
      .getCheckInPreferredComs()
      .find('.govuk-radios__item')
      .eq(0)
      .find('.govuk-radios__input')
      .click()
    contactPreferencePage.getSubmitBtn().click()
    const takeAPhotoOptionsPage = new TakeAPhotoOptionsPage()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    takeAPhotoOptionsPage.getBackLink().click()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    const takeAPhotoPage = new TakeAPhotoPage()
    takeAPhotoPage.checkOnPage()
    takeAPhotoPage.getSubmitBtn().click()
    const photoRules = new PhotoRulesPage()
    photoRules.checkOnPage()
    photoRules.getSubmitBtn().click()
    const checkYourAnswersPage = new CheckYourAnswersPage()
    checkYourAnswersPage.checkOnPage()

    // Date change
    checkYourAnswersPage.getElementData('dateAction').click()
    dateFrequencyPage.checkOnPage()
    dateFrequencyPage.getSubmitBtn().click()
    checkYourAnswersPage.checkOnPage()
    checkYourAnswersPage.getSummaryListRow(2).find('.govuk-summary-list__value').should('contain.text', 'Every week')
    checkYourAnswersPage.getElementData('intervalAction').click()
    dateFrequencyPage.checkOnPage()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(2).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    checkYourAnswersPage.checkOnPage()
    checkYourAnswersPage.getSummaryListRow(2).find('.govuk-summary-list__value').should('contain.text', 'Every 4 weeks')

    // Contact preference change
    checkYourAnswersPage.getSummaryListRow(3).find('.govuk-summary-list__value').should('contain.text', 'Text message')
    checkYourAnswersPage.getElementData('preferredComsAction').click()
    contactPreferencePage.checkOnPage()
    contactPreferencePage
      .getCheckInPreferredComs()
      .find('.govuk-radios__item')
      .eq(1)
      .find('.govuk-radios__input')
      .click()
    contactPreferencePage.getSubmitBtn().click()
    checkYourAnswersPage.checkOnPage()
    checkYourAnswersPage.getSummaryListRow(3).find('.govuk-summary-list__value').should('contain.text', 'Email')

    // Mobile
    checkYourAnswersPage.getElementData('checkInMobileAction').click()
    contactPreferencePage.checkOnPage()
    contactPreferencePage.getChangeLink().click()
    const editContactPreferencePage = new EditContactPreferencePage()
    editContactPreferencePage.checkOnPage()
    editContactPreferencePage.getSubmitBtn().click()
    contactPreferencePage.checkOnPage()
    contactPreferencePage.getSubmitBtn().click()
    checkYourAnswersPage.checkOnPage()

    // photo options
    checkYourAnswersPage
      .getSummaryListRow(6)
      .find('.govuk-summary-list__value')
      .should('contain.text', 'Take a photo using this device')
    checkYourAnswersPage.getElementData('photoUploadOptionAction').click()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(1).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    const uploadAPhoto = new UploadAPhotoPage()
    uploadAPhoto.checkOnPage()
    uploadAPhoto.uploadPhoto('person.jpg')
    uploadAPhoto.continueButton().click()

    photoRules.checkOnPage()
    photoRules.getSubmitBtn().click()
    checkYourAnswersPage.checkOnPage()
    checkYourAnswersPage
      .getSummaryListRow(6)
      .find('.govuk-summary-list__value')
      .should('contain.text', 'Upload a photo')
  })
})

context('check-ins error scenario ', () => {
  it('should show error page when update fails with 404 HTTP response code', () => {
    loadPage()
    cy.task('stubUpdatePersonalContact404Response')
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.getDatePickerToggle().click()
    dateFrequencyPage.getNextDayButton().click()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    const contactPreferencePage = new ContactPreferencePage()
    contactPreferencePage.checkOnPage()
    contactPreferencePage.getChangeLink().click()
    const editContactPreferencePage = new EditContactPreferencePage()
    editContactPreferencePage.checkOnPage()
    editContactPreferencePage.getSubmitBtn().click()
    const errorPage = new ErrorPage()
    errorPage.checkPageTitle('Page not found')
  })

  it('should show error page when update fails with 500 HTTP response code', () => {
    loadPage()
    cy.task('stubUpdatePersonalContact500Response')
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.getDatePickerToggle().click()
    dateFrequencyPage.getNextDayButton().click()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    const contactPreferencePage = new ContactPreferencePage()
    contactPreferencePage.checkOnPage()
    contactPreferencePage.getChangeLink().click()
    const editContactPreferencePage = new EditContactPreferencePage()
    editContactPreferencePage.checkOnPage()
    editContactPreferencePage.getSubmitBtn().click()
    const errorPage = new ErrorPage()
    errorPage.checkPageTitle('Sorry, there is a problem with the service')
  })

  it('Should able to show error message when same phone / email already registered', () => {
    loadPage()
    cy.task('stubOffenderSetup422Response')
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.getDatePickerToggle().click()
    dateFrequencyPage.getNextDayButton().click()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    const contactPreferencePage = new ContactPreferencePage()
    contactPreferencePage.checkOnPage()
    contactPreferencePage
      .getCheckInPreferredComs()
      .find('.govuk-radios__item')
      .eq(0)
      .find('.govuk-radios__input')
      .click()
    contactPreferencePage.getSubmitBtn().click()
    const takeAPhotoOptionsPage = new TakeAPhotoOptionsPage()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    takeAPhotoOptionsPage.getBackLink().click()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(1).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    const uploadAPhoto = new UploadAPhotoPage()
    uploadAPhoto.checkOnPage()
    uploadAPhoto.uploadPhoto('person.jpg')
    uploadAPhoto.continueButton().click()
    const photoRules = new PhotoRulesPage()
    photoRules.checkOnPage()
    photoRules.getSubmitBtn().click()
    const checkYourAnswersPage = new CheckYourAnswersPage()
    checkYourAnswersPage.checkOnPage()
    checkYourAnswersPage.getSubmitBtn().click()
    checkYourAnswersPage
      .getErrorText()
      .should(
        'contain.text',
        "The email address or phone number you've entered is already associated with another person",
      )
  })

  it('Should able to show check ins registration error message', () => {
    loadPage()
    cy.task('stubOffenderSetup500Response')
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.getDatePickerToggle().click()
    dateFrequencyPage.getNextDayButton().click()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    const contactPreferencePage = new ContactPreferencePage()
    contactPreferencePage.checkOnPage()
    contactPreferencePage
      .getCheckInPreferredComs()
      .find('.govuk-radios__item')
      .eq(0)
      .find('.govuk-radios__input')
      .click()
    contactPreferencePage.getSubmitBtn().click()
    const takeAPhotoOptionsPage = new TakeAPhotoOptionsPage()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    takeAPhotoOptionsPage.getBackLink().click()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(1).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    const uploadAPhoto = new UploadAPhotoPage()
    uploadAPhoto.checkOnPage()
    uploadAPhoto.uploadPhoto('person.jpg')
    uploadAPhoto.continueButton().click()
    const photoRules = new PhotoRulesPage()
    photoRules.checkOnPage()
    photoRules.getSubmitBtn().click()
    const checkYourAnswersPage = new CheckYourAnswersPage()
    checkYourAnswersPage.checkOnPage()
    checkYourAnswersPage.getSubmitBtn().click()
    checkYourAnswersPage.getErrorText().should('contain.text', 'An error occurred during registration')
  })

  it('Should able to show error page, when checkin registration fails', () => {
    loadPage()
    cy.task('stubOffenderSetupComplete500Response')
    cy.get('[data-qa="online-checkin-btn"]').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.getSubmitBtn().click()
    const dateFrequencyPage = new DateFrequencyPage()
    dateFrequencyPage.getDatePickerToggle().click()
    dateFrequencyPage.getNextDayButton().click()
    dateFrequencyPage.getFrequency().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    dateFrequencyPage.getSubmitBtn().click()
    const contactPreferencePage = new ContactPreferencePage()
    contactPreferencePage.checkOnPage()
    contactPreferencePage
      .getCheckInPreferredComs()
      .find('.govuk-radios__item')
      .eq(0)
      .find('.govuk-radios__input')
      .click()
    contactPreferencePage.getSubmitBtn().click()
    const takeAPhotoOptionsPage = new TakeAPhotoOptionsPage()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(0).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    takeAPhotoOptionsPage.getBackLink().click()
    takeAPhotoOptionsPage.checkOnPage()
    takeAPhotoOptionsPage.getPhotoOptions().find('.govuk-radios__item').eq(1).find('.govuk-radios__input').click()
    takeAPhotoOptionsPage.getSubmitBtn().click()
    const uploadAPhoto = new UploadAPhotoPage()
    uploadAPhoto.checkOnPage()
    uploadAPhoto.uploadPhoto('person.jpg')
    uploadAPhoto.continueButton().click()
    const photoRules = new PhotoRulesPage()
    photoRules.checkOnPage()
    photoRules.getSubmitBtn().click()
    const checkYourAnswersPage = new CheckYourAnswersPage()
    checkYourAnswersPage.checkOnPage()
    checkYourAnswersPage.getSubmitBtn().click()
    cy.get('h1').should('contain.text', statusErrors[500].title)
    cy.get('[data-qa="errorMessage"]').should('contain.html', statusErrors[500].message)
  })
})

context('check-ins overview and manage pages', () => {
  it('should show online check ins section with check in details', () => {
    cy.task('resetMocks')
    cy.task('stubEnableESuperVision')
    cy.visit(`/case/X778160`)
    const overviewPage = new OverviewPage()
    overviewPage.checkOnPage()
    overviewPage.getElementData('checkinCard').should('contain.text', 'Online check ins')
    overviewPage.getElementData('checkinCard').find('.app-summary-card__actions').should('exist')
    overviewPage.getElementData('firstCheckInDueLabel').should('contain.text', 'First check in')
    overviewPage.getElementData('firstCheckInValue').should('contain.text', 'Monday 3 November')
    overviewPage.getElementData('frequencyLabel').should('contain.text', 'Frequency')
    overviewPage.getElementData('frequencyValue').should('contain.text', 'Every week')
    overviewPage.getElementData('checkinCard').find('.app-summary-card__actions').should('exist')
    overviewPage
      .getElementData('checkinCard')
      .find('.govuk-link')
      .should('contain.text', 'View all online check in details')
  })

  it('should show online check ins due section ', () => {
    cy.task('resetMocks')
    cy.task('stubEnableESuperVision')
    cy.visit(`/case/X000001`)
    const overviewPage = new OverviewPage()
    overviewPage.checkOnPage()
    overviewPage.getElementData('checkinCard').should('contain.text', 'Online check ins')
    overviewPage.getElementData('checkinCard').find('.app-summary-card__actions').should('exist')
    overviewPage.getElementData('checkinDueLabel').should('contain.text', 'Next check in due')
    overviewPage.getElementData('checkinDueValue').should('contain.text', 'Online check ins not set up')
    overviewPage.getElementData('checkinCard').find('.app-summary-card__actions').should('exist')
    overviewPage.getElementData('checkinCard').find('.govuk-link').should('contain.text', 'Set up online check ins')
    overviewPage.getElementData('checkinCard').find('.govuk-link').click()
    const instructionsPage = new InstructionsPage()
    instructionsPage.checkOnPage()
    instructionsPage.getBackLink().click()
    overviewPage.checkOnPage()
  })

  it('should show checkin details', () => {
    cy.task('resetMocks')
    cy.task('stubEnableESuperVision')
    cy.visit(`/case/X778160`)
    const overviewPage = new OverviewPage()
    overviewPage.checkOnPage()
    overviewPage
      .getElementData('checkinCard')
      .find('.govuk-link')
      .should('contain.text', 'View all online check in details')
    overviewPage.getElementData('checkinCard').find('.govuk-link').click()

    const manageCheckins = new ManageCheckins()
    manageCheckins.checkOnPage()
    manageCheckins.getElementData('checkinSettingsCard').should('contain.text', 'Check in settings')
    manageCheckins.getElementData('firstCheckInDueLabel').should('contain.text', 'First check in')
    manageCheckins.getElementData('firstCheckInValue').should('contain.text', 'Monday 3 November')
    manageCheckins.getElementData('frequencyLabel').should('contain.text', 'Frequency')
    manageCheckins.getElementData('frequencyValue').should('contain.text', 'Every week')
    manageCheckins.getElementData('checkinSettingsCard').find('.govuk-link').should('contain.text', 'Change')

    manageCheckins.getElementData('checkinContactCard').should('contain.text', 'Contact details')
    manageCheckins.getElementData('checkinContactCard').find('.govuk-link').should('contain.text', 'Change')
    manageCheckins.getElementData('emailAddressLabel').should('contain.text', 'Email address')
    manageCheckins.getElementData('emailAddressValue').should('contain.text', 'address1@gmail.com')
    manageCheckins.getElementData('mobileNumberLabel').should('contain.text', 'Mobile number')
    manageCheckins.getElementData('mobileNumberValue').should('contain.text', '071838893')
  })
})
