version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "21:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:00"
      timezone: "Europe/London"
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github/actions/setup-zap"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:00"
      timezone: "Europe/London"
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
