FROM ghcr.io/ministryofjustice/hmpps-node:24-alpine AS base

COPY package*.json ./
COPY .npmrc* ./

RUN npm install

COPY . .

RUN node esbuild/esbuild.config.js --build

EXPOSE 3007

CMD ["node", "esbuild/esbuild.config.js", "--feature-dev-server"]