services:
  wiremock:
    image: wiremock/wiremock:3.13.1
    container_name: mpop-wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile.feature-dev
    container_name: mpop-app
    environment:
      - PORT=3007
      - NODE_ENV=development
      - ENVIRONMENT_NAME=local
      - REDIS_ENABLED=false
      - HMPPS_AUTH_URL=http://wiremock:8080/auth
      - MANAGE_USERS_API_URL=http://wiremock:8080/manage-users-api
      - TOKEN_VERIFICATION_API_URL=http://wiremock:8080/verification
      - TOKEN_VERIFICATION_ENABLED=true
      - MAS_API_URL=http://wiremock:8080/mas
      - DELIUS_API_URL=http://wiremock:8080/delius
      - ARNS_API_URL=http://wiremock:8080/arns
      - TIER_API_URL=http://wiremock:8080/tier
      - FLIPT_URL=http://wiremock:8080/flipt
      - INTERVENTIONS_API_URL=http://wiremock:8080/interventions
      - SUPERVISION_API_URL=http://wiremock:8080/supervision
      - ARNS_ASSESSMENT_PLATFORM_API_URL=http://wiremock:8080/assessment-platform
      - PROBATION_FRONTEND_COMPONENTS_API_URL=http://wiremock:8080/probation-frontend-components
      - E_SUPERVISION_API_URL=http://wiremock:8080/esupervision
      - AUDIT_ENABLED=false
      - API_CLIENT_ID=clientid
      - API_CLIENT_SECRET=clientsecret
      - SYSTEM_CLIENT_ID=clientid
      - SYSTEM_CLIENT_SECRET=clientsecret
    ports:
      - "3007:3007"
    depends_on:
      - wiremock

  waf:
    image: owasp/modsecurity-crs:4.25-nginx-lts
    container_name: modsec-waf
    ports:
      - "8081:8080"
    environment:
      BACKEND: "http://app:3007"
      SERVER_NAME: "localhost"
      MODSEC_RULE_ENGINE: "On"
      MODSEC_AUDIT_ENGINE: "On"
      MODSEC_AUDIT_LOG: "/var/log/nginx/error.log"
      MODSEC_AUDIT_LOG_TYPE: "Serial"
      BLOCKING_PARANOIA: "2"
      DETECTION_PARANOIA: "2"
    volumes:
      - ./waf-conf/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:ro
      - ./waf-conf/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:ro
    depends_on:
      - app