FROM ghcr.io/ministryofjustice/hmpps-node:24-alpine AS base

WORKDIR /app

RUN apk add --no-cache \
    python3 \
    python3-dev \
    build-base \
    ca-certificates

COPY package*.json ./
COPY .npmrc* ./

RUN npm install

COPY . .

RUN node esbuild/esbuild.config.js --build

EXPOSE 3007

CMD ["node", "esbuild/esbuild.config.js", "--feature-dev-server"]