services:
  app:
    build:
      context: .
      args:
        BUILD_NUMBER: "1.0.0"
        GIT_REF: "a1b2c3"
        GIT_BRANCH: "main"
      secrets:
        - sentry
    networks:
      - hmpps
    ports:
      - "3000:3000"
    env_file:
      - .env

networks:
  hmpps:

secrets:
  sentry:
    file: .sentry-token