#sonar.host.url=https://sonarcloud.io
sonar.organization=ministryofjustice
sonar.projectKey=ministryofjustice_hmpps-manage-a-supervision-ui
sonar.javascript.lcov.reportPaths=test_results/jest/lcov.info,coverage/lcov.info
sonar.sources=server
sonar.coverage.exclusions=".*.test.ts","node_modules","integration_tests","wiremock","server/@types",".*jest.config.js","server/app.ts","server/index.ts",".*.cy.ts"
