import Page from '../pages/page'
import ActivityLogPage from '../pages/activityLog'
import ErrorPage from '../pages/error'
import { activityLogValidation } from '../../server/properties/validation/activityLog'
import { getErrorMessage } from '../utils/index'
import ManageAppointmentPage from '../pages/appointments/manage-appointment.page'

const keywords = 'Phone call'
const dateFrom = '11/1/2025'
const dateTo = '12/1/2025'

const fillFilters = (page: ActivityLogPage) => {
  page.getKeywordsInput().type(keywords)
  page.getDateFromInput().type(dateFrom)
  page.getDateToInput().type(dateTo)
  page.getComplianceFilter(1).click()
  page.getComplianceFilter(2).click()
  page.getComplianceFilter(3).click()
}

const filtersAreFilled = (page: ActivityLogPage) => {
  page.getKeywordsInput().should('have.value', keywords)
  page.getDateFromInput().should('have.value', dateFrom)
  page.getDateToInput().should('have.value', dateTo)
  page.getComplianceFilter(1).should('be.checked')
  page.getComplianceFilter(2).should('be.checked')
  page.getComplianceFilter(3).should('be.checked')
}

context('Contacts', () => {
  const today = new Date()
  const day = today.getDate()
  const month = today.getMonth() + 1
  const year = today.getFullYear()
  const date = `${day}/${month}/${year}`

  beforeEach(() => {
    cy.task('resetMocks')
  })

  it('should render the 404 error page if CRN does not exist', () => {
    cy.visit('/case/XXXXXXX/activity-log', { failOnStatusCode: false })
    const page = new ErrorPage()
    page.checkPageTitle('Page not found')
  })
  it('should render the contacts results', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    cy.get('.govuk-table').should('exist')
    cy.get('.govuk-table__header').eq(0).should('contain.text', 'Date')
    cy.get('.govuk-table__header').eq(1).should('contain.text', 'Contact')
    cy.get('.govuk-table__header').eq(2).should('contain.text', 'Actions')
    page.getActivityViewNoNotes(1).should('contain.text', 'Planned video contact (NS)')
    page.getActivityTitle(2).should('contain.text', 'Phone call')
    page.getActivityViewLink(0).should('have.attr', 'href').and('include', '/case/X000001/')
  })
  it('should render the page with date of death recorded warning', () => {
    cy.task('stubPersonalDetailsDateOfDeath')
    cy.visit('/case/X000001/activity-log')
    cy.get('[data-qa="dateOfDeathWarning"]').should('contain.text', 'There is a date of death recorded for Caroline.')
  })
  it('should render the filter menu', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    cy.get('[data-qa="filter-form"]').within(() => cy.get('h2').should('contain.text', 'Filter contacts'))
    page.getApplyFiltersButton().should('contain.text', 'Apply filters')
    page.getSelectedFiltersBox().should('not.exist')
    cy.get('[data-qa="keywords"]').within(() => cy.get('label').should('contain.text', 'Keywords'))
    page.getKeywordsInput().should('exist').should('have.value', '')
    cy.get('[data-qa="date-from"]').within(() => cy.get('label').should('contain.text', 'Date from'))
    cy.get('[data-qa="date-from"]').within(() => cy.get('input').should('exist').should('have.value', ''))
    cy.get('[data-qa="date-to"]').within(() => cy.get('label').should('contain.text', 'Date to'))
    cy.get('[data-qa="date-to"]').within(() => cy.get('input').should('exist').should('have.value', ''))
    cy.get('[data-qa="compliance"]').within(() =>
      cy.get('legend').should('exist').should('contain.text', 'Compliance filters'),
    )
    const filters = ['Without an outcome', 'Complied', 'Not complied']
    cy.get('[data-qa="compliance"] .govuk-checkboxes__item').each(($el, i) => {
      cy.wrap($el).find('input').should('not.be.checked')
      cy.wrap($el).find('label').should('contain.text', filters[i])
    })
    page.getActivityViewLink(0).should('exist')
  })
  it('should show the correct validation if date to is selected, but no date from is selected', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getDateToToggle().click()
    page.getDateToDialog().should('be.visible').find(`button[data-testid="${date}"]`).click()
    page.getDateToInput().should('have.value', date)
    page.getDateToDialog().should('not.be.visible')
    page.getApplyFiltersButton().click()
    page.getSelectedFilterTag(1).should('not.exist')
    page.getErrorSummaryBox().should('be.visible')
    page.getAllErrorSummaryLinks().should('have.length', 1)
    page
      .getErrorSummaryLink(0)
      .should('contain.text', getErrorMessage(activityLogValidation(), 'dateFrom', 'isNotEmpty'))
    page.getErrorSummaryLink(0).click()
    page.getDateFromInput().should('be.focused')
  })
  it('should show the correct validation if date from is selected, but no date to is selected', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getDateFromToggle().click()
    page.getDateFromDialog().should('be.visible').find(`button[data-testid="${date}"]`).click()
    page.getDateFromInput().should('have.value', date)
    page.getDateFromDialog().should('not.be.visible')
    page.getApplyFiltersButton().click()
    page.getSelectedFilterTag(1).should('not.exist')
    page.getErrorSummaryBox().should('be.visible')
    page.getAllErrorSummaryLinks().should('have.length', 1)
    page.getErrorSummaryLink(0).should('contain.text', getErrorMessage(activityLogValidation(), 'dateTo', 'isNotEmpty'))
    page.getErrorSummaryLink(0).click()
    page.getDateToInput().should('be.focused')
  })
  it('should show the correct validation if an invalid date from is entered', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getDateFromInput().type('0104/2025')
    page.getApplyFiltersButton().click()
    page.getSelectedFilterTag(1).should('not.exist')
    page.getErrorSummaryBox().should('be.visible')
    page.getAllErrorSummaryLinks().should('have.length', 2)
    page
      .getErrorSummaryLink(0)
      .should('contain.text', getErrorMessage(activityLogValidation(), 'dateFrom', 'isValidDate'))
    page.getErrorSummaryLink(1).should('contain.text', getErrorMessage(activityLogValidation(), 'dateTo', 'isNotEmpty'))
  })
  it('should show the correct validation if an invalid date to is entered', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getDateToInput().type('01/04/')
    page.getApplyFiltersButton().click()
    page.getSelectedFilterTag(1).should('not.exist')
    page.getErrorSummaryBox().should('be.visible')
    page.getAllErrorSummaryLinks().should('have.length', 2)
    page
      .getErrorSummaryLink(0)
      .should('contain.text', getErrorMessage(activityLogValidation(), 'dateFrom', 'isNotEmpty'))
    page
      .getErrorSummaryLink(1)
      .should('contain.text', getErrorMessage(activityLogValidation(), 'dateTo', 'isValidDate'))
  })
  it('should show the correct validation if date from doesnt exist', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getDateFromInput().type('30/2/2025')
    page.getApplyFiltersButton().click()
    page.getSelectedFilterTag(1).should('not.exist')
    page.getErrorSummaryBox().should('be.visible')
    page.getAllErrorSummaryLinks().should('have.length', 2)
    page
      .getErrorSummaryLink(0)
      .should('contain.text', getErrorMessage(activityLogValidation(), 'dateFrom', 'isValidDate'))
    page.getErrorSummaryLink(1).should('contain.text', getErrorMessage(activityLogValidation(), 'dateTo', 'isNotEmpty'))
  })
  it('should show the correct validation if date to doesnt exist', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getDateToInput().type('30/2/2025')
    page.getApplyFiltersButton().click()
    page.getSelectedFilterTag(1).should('not.exist')
    page.getErrorSummaryBox().should('be.visible')
    page.getAllErrorSummaryLinks().should('have.length', 2)
    page
      .getErrorSummaryLink(0)
      .should('contain.text', getErrorMessage(activityLogValidation(), 'dateFrom', 'isNotEmpty'))
    page
      .getErrorSummaryLink(1)
      .should('contain.text', getErrorMessage(activityLogValidation(), 'dateTo', 'isValidDate'))
  })
  it('should show the correct validation if date to is before date from', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getDateFromInput().type('12/1/2025')
    page.getDateToInput().type('11/1/2025')
    page.getApplyFiltersButton().click()
    page.getSelectedFilterTag(1).should('not.exist')
    page.getErrorSummaryBox().should('be.visible')
    page.getAllErrorSummaryLinks().should('have.length', 1)
    page
      .getErrorSummaryLink(0)
      .should('contain.text', getErrorMessage(activityLogValidation(), 'dateTo', 'isNotLaterThan'))
  })

  it('should show the correct validation if date from is in the future', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getDateFromInput().type(`${day}/${month}/${year + 1}`)
    page.getApplyFiltersButton().click()
    page.getErrorSummaryBox().should('be.visible')
    page.getAllErrorSummaryLinks().should('have.length', 2)
    page
      .getErrorSummaryLink(0)
      .should('contain.text', getErrorMessage(activityLogValidation(), 'dateFrom', 'isNotLaterThanToday'))
    page.getErrorSummaryLink(1).should('contain.text', getErrorMessage(activityLogValidation(), 'dateTo', 'isNotEmpty'))
  })
  it('should show the correct validation if date to is in the future', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getDateToInput().type(`${day}/${month}/${year + 1}`)
    page.getApplyFiltersButton().click()
    page.getErrorSummaryBox().should('be.visible')
    page.getAllErrorSummaryLinks().should('have.length', 2)
    page
      .getErrorSummaryLink(0)
      .should('contain.text', getErrorMessage(activityLogValidation(), 'dateFrom', 'isNotEmpty'))
    page
      .getErrorSummaryLink(1)
      .should('contain.text', getErrorMessage(activityLogValidation(), 'dateTo', 'isNotLaterThanToday'))
  })
  it('should display the filter tag and filter the list if a keyword value is submitted', () => {
    cy.visit('/case/X000001/activity-log')
    const value = 'Phone call'
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getKeywordsInput().type(value)
    page.getApplyFiltersButton().click()
    page.getSelectedFiltersBox().find('h2').should('contain.text', 'Selected filters')
    page.getSelectedFiltersBox().find('h3:nth-of-type(1)').should('contain.text', 'Search term')
    page.getSelectedFilterTags().should('have.length', 1)
    page.getSelectedFilterTag(1).should('contain.text', value)
    page.getActivityTitle(1).should('contain.text', 'Phone call')
    page.getKeywordsInput().should('have.value', value)
  })
  it('should remove the tag, clear the keyword field and reset the list if the keyword tag is clicked', () => {
    cy.visit('/case/X000001/activity-log')
    const value = 'Phone call'
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getKeywordsInput().type(value)
    page.getApplyFiltersButton().click()
    page.getSelectedFilterTag(1).click()
    page.getSelectedFilterTag(1).should('not.exist')
    page.getSelectedFiltersBox().should('not.exist')
    page.getKeywordsInput().should('have.value', '')
    page.getActivityViewNoNotes(1).should('contain.text', 'Planned video contact (NS)')
  })
  it('should display the filter tag and filter the list if a date from and date to are submitted', () => {
    cy.visit('/case/X000001/activity-log')
    const fromDate = '20/1/2025'
    const toDate = '27/1/2025'
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getDateFromInput().type(fromDate)
    page.getDateToInput().type(toDate)
    page.getApplyFiltersButton().click()
    page.getSelectedFiltersBox().find('h3:nth-of-type(1)').should('contain.text', 'Date range')
    page.getDateFromInput().should('have.value', fromDate)
    page.getDateToInput().should('have.value', toDate)
    page.getSelectedFilterTags().should('have.length', 1)
    page.getSelectedFilterTag(1).should('contain.text', `${fromDate} - ${toDate}`)
    cy.get('.contact-activity__actions-cell').should('have.length', 1)
    cy.get('[data-qa="results-count-start"]').should('contain.text', '1')
    cy.get('[data-qa="results-count-end"]').should('contain.text', '1')
    cy.get('[data-qa="results-count-total"]').should('contain.text', '1')
  })
  it('should remove the tag, clear both date fields and reset the list if the date range tag is clicked', () => {
    cy.visit('/case/X000001/activity-log')
    const fromDate = '20/1/2025'
    const toDate = '27/1/2025'
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getDateFromInput().type(fromDate)
    page.getDateToInput().type(toDate)
    page.getApplyFiltersButton().click()
    page.getSelectedFilterTag(1).click()
    page.getSelectedFilterTag(1).should('not.exist')
    page.getSelectedFiltersBox().should('not.exist')
    page.getDateFromInput().should('have.value', '')
    page.getDateToInput().should('have.value', '')
    page.getActivityViewNoNotes(1).should('contain.text', 'Planned video contact (NS)')
    cy.get('[data-qa="results-count-start"]').should('contain.text', '1')
    cy.get('[data-qa="results-count-end"]').should('contain.text', '25')
    cy.get('[data-qa="results-count-total"]').should('contain.text', '54')
  })
  it('should display the 3 filter tags and filter the list if all compliance filters as clicked and submitted', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getComplianceFilter(1).click()
    page.getComplianceFilter(2).click()
    page.getComplianceFilter(3).click()
    page.getApplyFiltersButton().click()
    page.getSelectedFiltersBox().find('h3:nth-of-type(1)').should('contain.text', 'Compliance filters')
    page.getSelectedFiltersBox().should('exist')
    page.getComplianceFilter(1).should('be.checked')
    page.getComplianceFilter(2).should('be.checked')
    page.getComplianceFilter(3).should('be.checked')
    page.getSelectedFilterTags().should('have.length', 3)
    page.getSelectedFilterTag(1).should('contain.text', 'Without an outcome')
    page.getSelectedFilterTag(2).should('contain.text', 'Complied')
    page.getSelectedFilterTag(3).should('contain.text', 'Not complied')
    page.getActivityTitle(1).should('contain.text', 'AP PA - attitudes, thinking & behaviours')
    page.getActivityTitle(2).should('contain.text', 'Pre-intervention session 1')
    page.getActivityTitle(3).should('contain.text', 'Initial appointment - home visit (NS)')
    cy.get('[data-qa="results-count-start"]').should('contain.text', '1')
    cy.get('[data-qa="results-count-end"]').should('contain.text', '3')
    cy.get('[data-qa="results-count-total"]').should('contain.text', '3')
  })
  it(`should display 2 filter tags, uncheck the filter option and filter the list when 'Not complied' tag is clicked`, () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getComplianceFilter(1).click()
    page.getComplianceFilter(2).click()
    page.getComplianceFilter(3).click()
    page.getApplyFiltersButton().click()
    page.getSelectedFilterTag(3).click()
    page.getSelectedFilterTags().should('have.length', 2)
    page.getSelectedFilterTag(1).should('contain.text', 'Without an outcome')
    page.getSelectedFilterTag(2).should('contain.text', 'Complied')
    page.getSelectedFilterTag(3).should('not.exist')
    page.getComplianceFilter(1).should('be.checked')
    page.getComplianceFilter(2).should('be.checked')
    page.getComplianceFilter(3).should('not.be.checked')
    page.getActivityTitle(1).should('contain.text', 'AP PA - attitudes, thinking & behaviours')
    page.getActivityTitle(2).should('contain.text', 'Pre-intervention session 1')
    cy.get('[data-qa="results-count-start"]').should('contain.text', '1')
    cy.get('[data-qa="results-count-end"]').should('contain.text', '2')
    cy.get('[data-qa="results-count-total"]').should('contain.text', '2')
  })
  it(`should display 1 filter tag, uncheck the deselected filter options and filter the list when 'complied' and 'Not complied' tags are clicked`, () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getComplianceFilter(1).click()
    page.getComplianceFilter(2).click()
    page.getComplianceFilter(3).click()
    page.getApplyFiltersButton().click()
    page.getSelectedFilterTag(3).click()
    page.getSelectedFilterTag(2).click()
    page.getSelectedFilterTags().should('have.length', 1)
    page.getSelectedFilterTag(1).should('contain.text', 'Without an outcome')
    page.getSelectedFilterTag(2).should('not.exist')
    page.getSelectedFilterTag(3).should('not.exist')
    page.getComplianceFilter(1).should('be.checked')
    page.getComplianceFilter(2).should('not.be.checked')
    page.getComplianceFilter(3).should('not.be.checked')
  })
  it(`should clear all selected filters when 'Clear filters' link is clicked`, () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getKeywordsInput().type('Phone call')
    page.getDateFromInput().type('20/1/2025')
    page.getDateToInput().type('27/1/2025')
    page.getComplianceFilter(1).click()
    page.getComplianceFilter(2).click()
    page.getComplianceFilter(3).click()
    page.getApplyFiltersButton().click()
    page.getSelectedFiltersBox().find('h3:nth-of-type(1)').should('contain.text', 'Search term')
    page.getSelectedFiltersBox().find('h3:nth-of-type(2)').should('contain.text', 'Date range')
    page.getSelectedFiltersBox().find('h3:nth-of-type(3)').should('contain.text', 'Compliance filters')
    page.getSelectedFilterTags().should('have.length', 5)
    page.getActivityTitle(1).should('contain.text', 'Phone call')
    cy.get('[data-qa="results-count-start"]').should('contain.text', '1')
    cy.get('[data-qa="results-count-end"]').should('contain.text', '1')
    cy.get('[data-qa="results-count-total"]').should('contain.text', '1')
    cy.get('.govuk-pagination').should('not.exist')
    cy.get('.moj-filter__heading-action a').click()
    page.getSelectedFiltersBox().should('not.exist')
    page.getSelectedFilterTags().should('not.exist')
    page.getKeywordsInput().should('have.value', '')
    page.getDateFromInput().should('have.value', '')
    page.getDateToInput().should('have.value', '')
    page.getComplianceFilter(1).should('not.be.checked')
    page.getComplianceFilter(2).should('not.be.checked')
    page.getComplianceFilter(3).should('not.be.checked')
    page.getActivityViewNoNotes(1).should('contain.text', 'Planned video contact (NS)')
    cy.get('[data-qa="results-count-start"]').should('contain.text', '1')
    cy.get('[data-qa="results-count-end"]').should('contain.text', '25')
    cy.get('[data-qa="results-count-total"]').should('contain.text', '54')
    cy.get('.govuk-pagination').should('exist')
  })
  it('Contacts page renders activities with View and Manage links', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    cy.get('.govuk-table').should('exist')
    page.getActivityViewNoNotes(1).should('contain.text', 'Planned video contact (NS)')
    page.getActivityTitle(2).should('contain.text', 'Phone call')
    page.getActivityViewNoNotes(3).should('contain.text', 'Planned appointment')
    page.getActivityViewNotes(4).should('contain.text', 'Some notes')
    page.getActivityViewNotes(5).should('contain.text', 'Turned up')
    page.getActivityTitle(6).should('contain.text', 'Phone call')
    page.getActivityTitle(7).should('contain.text', 'Office appointment')
    page.getActivityViewLink(0).should('contain.text', 'View')
    page
      .getActivityViewLink(6)
      .should(
        'have.attr',
        'href',
        `/case/X000001/appointments/appointment/16/manage?back=${encodeURIComponent('/case/X000001/activity-log')}`,
      )
  })
  it('should link to the manage appointment page', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getActivityViewLink(6).click()
    Page.verifyOnPage(ManageAppointmentPage)
  })
  it('should display the pagination navigation', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    cy.get('.govuk-pagination').should('exist')
    cy.get('.govuk-pagination__link[rel="prev"]').should('not.exist')
    cy.get('.govuk-pagination__link[rel="next"]').should('exist')
    page.getPaginationLink(1).should('have.attr', 'aria-current')
    page.getPaginationLink(1).should('contain.text', '1')
    page.getPaginationLink(2).should('contain.text', '2')
    page.getPaginationLink(3).should('contain.text', '3')
    page.getPaginationItem(4).should('contain.text', '⋯')
    page.getPaginationLink(5).should('contain.text', '6')
    cy.get('.govuk-pagination__item').should('have.length', 5)
  })
  it('should link to the next page when link 2 is clicked', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getPaginationLink(2).click()
    page.getPaginationLink(2).should('have.attr', 'aria-current')
    page.getPaginationLink(1).should('not.have.attr', 'aria-current')
    cy.get('.govuk-pagination__link[rel="prev"]').should('exist')
    cy.get('.govuk-pagination__link[rel="next"]').should('exist')
    cy.get('.govuk-pagination__item').should('have.length', 5)
    page.getPaginationLink(1).should('contain.text', '1')
    page.getPaginationLink(2).should('contain.text', '2')
    page.getPaginationLink(3).should('contain.text', '3')
    page.getPaginationItem(4).should('contain.text', '⋯')
    page.getPaginationLink(5).should('contain.text', '6')
  })
  it('should link to the next page when link 3 is clicked', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getPaginationLink(3).click()
    page.getPaginationLink(3).should('not.have.attr', 'aria-current')
    page.getPaginationLink(4).should('have.attr', 'aria-current')
    cy.get('.govuk-pagination__link[rel="prev"]').should('exist')
    cy.get('.govuk-pagination__link[rel="next"]').should('exist')
    cy.get('.govuk-pagination__item').should('have.length', 7)
    page.getPaginationLink(1).should('contain.text', '1')
    page.getPaginationItem(2).should('contain.text', '⋯')
    page.getPaginationLink(3).should('contain.text', '2')
    page.getPaginationItem(4).should('contain.text', '3')
    page.getPaginationLink(5).should('contain.text', '4')
    page.getPaginationItem(6).should('contain.text', '⋯')
    page.getPaginationLink(7).should('contain.text', '6')
  })
  it('should link to page 2 when the previous link is clicked', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getPaginationLink(3).click()
    cy.get('.govuk-pagination__link[rel="prev"]').click()
    page.getPaginationLink(2).should('have.attr', 'aria-current')
    page.getPaginationLink(1).should('not.have.attr', 'aria-current')
    cy.get('.govuk-pagination__link[rel="prev"]').should('exist')
    cy.get('.govuk-pagination__link[rel="next"]').should('exist')
    cy.get('.govuk-pagination__item').should('have.length', 5)
    page.getPaginationLink(1).should('contain.text', '1')
    page.getPaginationLink(2).should('contain.text', '2')
    page.getPaginationLink(3).should('contain.text', '3')
    page.getPaginationItem(4).should('contain.text', '⋯')
    page.getPaginationLink(5).should('contain.text', '6')
  })
  it('should link to page 4 when the next link is clicked', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getPaginationLink(3).click()
    cy.get('.govuk-pagination__link[rel="next"]').click()
    page.getPaginationLink(3).should('not.have.attr', 'aria-current')
    page.getPaginationLink(4).should('have.attr', 'aria-current')
    cy.get('.govuk-pagination__link[rel="prev"]').should('exist')
    cy.get('.govuk-pagination__link[rel="next"]').should('exist')
    cy.get('.govuk-pagination__item').should('have.length', 7)
    page.getPaginationLink(1).should('contain.text', '1')
    page.getPaginationItem(2).should('contain.text', '⋯')
    page.getPaginationLink(3).should('contain.text', '3')
    page.getPaginationLink(4).should('contain.text', '4')
    page.getPaginationLink(5).should('contain.text', '5')
    page.getPaginationItem(6).should('contain.text', '⋯')
    page.getPaginationLink(7).should('contain.text', '6')
  })
  it('should link to the next page when the link 5 is clicked', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getPaginationLink(3).click()
    page.getPaginationLink(5).click()
    page.getPaginationLink(5).click()
    page.getPaginationLink(3).should('not.have.attr', 'aria-current')
    page.getPaginationLink(4).should('have.attr', 'aria-current')
    cy.get('.govuk-pagination__link[rel="prev"]').should('exist')
    cy.get('.govuk-pagination__link[rel="next"]').should('exist')
    cy.get('.govuk-pagination__item').should('have.length', 5)
    page.getPaginationLink(1).should('contain.text', '1')
    page.getPaginationItem(2).should('contain.text', '⋯')
    page.getPaginationLink(3).should('contain.text', '4')
    page.getPaginationLink(4).should('contain.text', '5')
    page.getPaginationLink(5).should('contain.text', '6')
  })
  it('should link to the next page when the link 6 is clicked', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getPaginationLink(3).click()
    page.getPaginationLink(5).click()
    page.getPaginationLink(5).click()
    page.getPaginationLink(5).click()
    page.getPaginationLink(4).should('not.have.attr', 'aria-current')
    page.getPaginationLink(5).should('have.attr', 'aria-current')
    cy.get('.govuk-pagination__link[rel="prev"]').should('exist')
    cy.get('.govuk-pagination__link[rel="next"]').should('not.exist')
    cy.get('.govuk-pagination__item').should('have.length', 5)
    page.getPaginationLink(1).should('contain.text', '1')
    page.getPaginationItem(2).should('contain.text', '⋯')
    page.getPaginationLink(3).should('contain.text', '4')
    page.getPaginationLink(4).should('contain.text', '5')
    page.getPaginationLink(5).should('contain.text', '6')
  })
  it('Contacts page renders activities in compact view', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    cy.get('.govuk-table').should('exist')
    page.getActivity(1).should('contain.text', 'Planned video contact (NS)')
    page.getActivity(2).should('contain.text', 'Phone call')
    page.getActivity(3).should('contain.text', 'Planned appointment')
    page.getActivity(4).should('contain.text', 'Initial appointment')
    page.getActivity(5).should('contain.text', 'Office appointment')
    page.getActivity(6).should('contain.text', 'Phone call')
    page.getActivity(7).should('contain.text', 'Office appointment')
    page.getActivity(8).should('contain.text', 'Initial appointment')
    page.getActivity(9).should('contain.text', 'Initial appointment')
    page.getActivity(10).should('contain.text', 'Planned video contact (NS)')
  })
  it('should display the no results message when no results are returned', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    page.getKeywordsInput().type('No results')
    page.getApplyFiltersButton().click()
    cy.get('[data-qa="results-count"]').should('not.exist')
    cy.get('.govuk-pagination').should('not.exist')
    page.getNoResults().find('h3').should('contain.text', '0 search results found')
    page.getNoResults().find('p').should('contain.text', 'Improve your search by:')
    page.getNoResults().find('li:nth-of-type(1)').should('contain.text', 'removing filters')
    page.getNoResults().find('li:nth-of-type(2)').should('contain.text', 'double-checking the spelling')
    page
      .getNoResults()
      .find('li:nth-of-type(3)')
      .should('contain.text', 'removing special characters like characters and accent letters')
    page
      .getNoResults()
      .find('li:nth-of-type(4)')
      .should('contain.text', 'using an asterisk (*) to search with a partial keyword, for example app*')
  })
  it('should persist the selected filters when a pagination link is clicked', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    fillFilters(page)
    page.getApplyFiltersButton().click()
    page.getPaginationItem(2).click()
    filtersAreFilled(page)
  })
  it('should persist the selected filters when user clicks on record detail link, then returns to the page via the breadcrumb', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    fillFilters(page)
    page.getApplyFiltersButton().click()
    page.getActivityViewLink(0).click()
    page.getBackLink().click()
    filtersAreFilled(page)
  })

  it('should render contacts when hide contact NDelius system generated contacts is checked', () => {
    cy.visit('/case/X000001/activity-log')
    const page = Page.verifyOnPage(ActivityLogPage)
    cy.get('[data-qa="filter-form"]').within(() => cy.get('h2').should('contain.text', 'Filter contacts'))
    page.getApplyFiltersButton().should('contain.text', 'Apply filters')
    page.getSelectedFiltersBox().should('not.exist')
    page.getElementByDataQA('submit-apply-button').should('contain.text', 'Apply')
    cy.get('[data-qa="filter-form"]').within(() => cy.get('h2').should('contain.text', 'Hide contacts'))
    page.getElementByDataQA('hideContact').find('input[type="checkbox"]').should('not.be.checked')
    page.getElementByDataQA('hideContact').find('input[type="checkbox"]').click()
    page.getElementByDataQA('submit-apply-button').click()

    cy.get('.govuk-table').should('exist')
    page.getActivity(1).should('contain.text', 'AP PA - attitudes, thinking & behaviours')
    page.getActivity(2).should('contain.text', 'Pre-intervention session 1')
  })
})
