{
 "title": "Flipt Evaluations",
 "description": "Specific evaluations metrics at the flag level.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "flag_key",
    "query": {
     "query": "label_values(flipt_evaluations_results_total, flag)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(flipt_evaluations_results_total, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Evaluation Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flipt_evaluations_requests_total{flag=\"$flag_key\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evaluation Result",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(value) (rate(flipt_evaluations_results_total{flag=\"$flag_key\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Match: {{match}} Reason: {{reason}} Segment: {{segment}} Value: {{value}}"
    }
   ]
  },
  {
   "title": "Evaluation Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(flipt_evaluations_latency_milliseconds_bucket{flag=\"$flag_key\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}