name: Get environment details
description: Map the GitHub environment name to the corresponding MOJ Cloud Platform namespace and Delius environment details

inputs:
  environment:
    description: GitHub environment name
    required: true

outputs:
  values-file:
    description: The filename for the values file containing environment configuration
    value: ${{ steps.cloud-platform.outputs.values-file }}
  cloud-platform-namespace:
    description: The name of the corresponding Cloud Platform namespace
    value: ${{ steps.cloud-platform.outputs.namespace }}
  delius-name:
    description: The full name of the corresponding Delius environment
    value: ${{ steps.delius.outputs.name }}
  delius-short-name:
    description: The short name of the corresponding Delius environment
    value: ${{ steps.delius.outputs.short-name }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Map GitHub environment to Cloud Platform namespace
      id: cloud-platform
      shell: bash
      run: |
        if [ '${{ inputs.environment }}' == 'dev' ];    then namespace='dev'; fi
        if [ '${{ inputs.environment }}' == 'preprod' ]; then namespace='preprod'; fi
        if [ '${{ inputs.environment }}' == 'prod' ];    then namespace='prod'; fi
        echo "namespace=${namespace}" | tee -a "$GITHUB_OUTPUT"
        echo "values-file=values-${namespace}.yml" | tee -a "$GITHUB_OUTPUT"


