generic-service:
  nameOverride: hmpps-manage-people-on-probation-ui
  productId: "HMPPS543" # productId for the product that this belongs too, i.e. DPS001, see README.md for details
  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-manage-people-on-probation-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=mpop-tech"
      SecRequestBodyAccess On
      SecResponseBodyAccess On
      
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"

      SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level=2"
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS"

      SecRule REQUEST_URI "/check-access" "id:101,phase:1,pass,t:none,nolog,ctl:ruleRemoveById=949110"
      SecRule REQUEST_URI "/edit-main-address" "id:102,phase:1,pass,t:none,nolog,ctl:ruleRemoveById=949110"

      # handle header already sent while sending to client, needs further investigation for potential fix
      SecRule REQUEST_URI "@rx ^\/case\/\w{7}" "id:103,phase:1,pass,t:none,nolog,ctl:ruleRemoveById=959100"
      SecRule REQUEST_URI "/recent-cases" "id:104,phase:1,pass,t:none,nolog,ctl:ruleRemoveById=959100"
      
      SecRule REQUEST_URI "@streq /id:105,phase:1,pass,t:none,nolog,ctl:ruleRemoveById=949110"

      # Send ModSecurity audit logs to the stdout (only for rejected requests)
      SecAuditLog /dev/stdout
      SecAuditLogFormat JSON
    tlsSecretName: hmpps-manage-people-on-probation-ui-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /metrics
    metricsPort: 3001

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_ENABLED: "true"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    AUDIT_SERVICE_NAME: "hmpps-manage-people-on-probation-ui"
    AUDIT_SQS_REGION: "eu-west-2"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-manage-people-on-probation-ui:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
    flipt:
      FLIPT_TOKEN: "API_TOKEN"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
    sentry:
      SENTRY_DSN: "SENTRY_DSN"
      SENTRY_LOADER_SCRIPT_ID: "SENTRY_LOADER_SCRIPT_ID"

  # https://github.com/ministryofjustice/hmpps-ip-allowlists/blob/main/ip-allowlist-groups.yaml 
  allowlist:
    groups:
      - digital_staff_and_mojo
      - unilink_staff
      - moj_cloud_platform

  serviceAccountName: manage-people-on-probation-ui

generic-prometheus-alerts:
  targetApplication: hmpps-manage-people-on-probation-ui
