---
# Per environment values which override defaults in hmpps-manage-people-on-probation-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-people-on-probation-preprod.hmpps.service.justice.gov.uk
    modsecurity_snippet: |
      SecRuleEngine On
      SecAuditEngine On
      SecAuditLog /var/log/nginx/error.log
      SecAuditLogType Serial
      SecDefaultAction "phase:2,pass,log,tag:github_team=hmpps-manage-people-on-probation,tag:namespace=hmpps-manage-people-on-probation-preprod"
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecAction \
        "id:900000,\
         phase:1,\
         nolog,\
         pass,\
         t:none,\
         setvar:tx.paranoia_level=2"
      
      SecRule REQUEST_URI "@rx ^/case/[^/]+/appointments/appointment/[^/]+/add-note$" \
        "id:100101,phase:1,pass,nolog,\
        ctl:ruleRemoveTargetByTag=attack-rce;ARGS:notes,\
        ctl:ruleRemoveTargetById=942430;ARGS:notes,\
        ctl:ruleRemoveTargetById=942200;ARGS:notes,\
        ctl:ruleRemoveTargetById=942360;ARGS:notes,\
        ctl:ruleRemoveTargetById=942131;ARGS:notes,\
        ctl:ruleRemoveTargetById=942370;ARGS:notes"
      
      SecRule REQUEST_FILENAME "@rx ^/case/[^/]+/arrange-appointment/[^/]+/add-note$" \
        "id:100107,phase:1,pass,nolog,\
        ctl:ruleRemoveTargetByTag=attack-rce;ARGS,\
        ctl:ruleRemoveTargetById=942430;ARGS,\
        ctl:ruleRemoveTargetById=942200;ARGS,\
        ctl:ruleRemoveTargetById=942360;ARGS,\
        ctl:ruleRemoveTargetById=942131;ARGS,\
        ctl:ruleRemoveTargetById=942370;ARGS"
      
      SecRule REQUEST_FILENAME "@rx ^/case/[^/]+/arrange-appointment/[^/]+/supporting-information$" \
        "id:100104,phase:1,pass,nolog,\
        ctl:ruleRemoveTargetByTag=attack-rce;ARGS,\
        ctl:ruleRemoveTargetById=942430;ARGS,\
        ctl:ruleRemoveTargetById=942200;ARGS,\
        ctl:ruleRemoveTargetById=942360;ARGS,\
        ctl:ruleRemoveTargetById=942131;ARGS,\
        ctl:ruleRemoveTargetById=942370;ARGS"
      
      SecRule REQUEST_URI "@rx ^/case/[^/]+/personal-details/edit-main-address$" \
        "id:100102,phase:1,pass,nolog,\
        ctl:ruleRemoveTargetByTag=attack-rce;ARGS:notes,\
        ctl:ruleRemoveTargetById=942430;ARGS:notes,\
        ctl:ruleRemoveTargetById=942200;ARGS:notes,\
        ctl:ruleRemoveTargetById=942360;ARGS:notes,\
        ctl:ruleRemoveTargetById=942131;ARGS:notes,\
        ctl:ruleRemoveTargetById=942370;ARGS:notes"
      
      SecRule REQUEST_FILENAME "@rx ^/case/[^/]+/appointments/[^/]+/check-in/review/(?:expired|identity|notes)$" \
        "id:100105,phase:1,pass,nolog,\
        ctl:ruleRemoveTargetByTag=attack-rce;ARGS,\
        ctl:ruleRemoveTargetById=942430;ARGS,\
        ctl:ruleRemoveTargetById=942200;ARGS,\
        ctl:ruleRemoveTargetById=942360;ARGS,\
        ctl:ruleRemoveTargetById=942131;ARGS,\
        ctl:ruleRemoveTargetById=942370;ARGS"
      
      SecRule REQUEST_FILENAME "@rx ^/case/[^/]+/appointments/[^/]+/check-in/(?:view|view-expired)$" \
        "id:100106,phase:1,pass,nolog,\
        ctl:ruleRemoveTargetByTag=attack-rce;ARGS,\
        ctl:ruleRemoveTargetById=942430;ARGS,\
        ctl:ruleRemoveTargetById=942200;ARGS,\
        ctl:ruleRemoveTargetById=942360;ARGS,\
        ctl:ruleRemoveTargetById=942131;ARGS,\
        ctl:ruleRemoveTargetById=942370;ARGS"

  env:
    INGRESS_URL: 'https://manage-people-on-probation-preprod.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in-preprod.hmpps.service.justice.gov.uk/auth'
    MANAGE_USERS_API_URL: 'https://manage-users-api-preprod.hmpps.service.justice.gov.uk'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api-preprod.prison.service.justice.gov.uk'
    MAS_API_URL: 'https://manage-supervision-and-delius-preprod.hmpps.service.justice.gov.uk'
    DELIUS_API_URL: 'https://manage-people-on-probation-and-delius-preprod.hmpps.service.justice.gov.uk'
    ARNS_API_URL: 'https://assess-risks-and-needs-preprod.hmpps.service.justice.gov.uk'
    TIER_API_URL: 'https://hmpps-tier-preprod.hmpps.service.justice.gov.uk'
    INTERVENTIONS_API_URL: 'https://hmpps-interventions-service-preprod.apps.live-1.cloud-platform.service.justice.gov.uk'
    SUPERVISION_API_URL: 'https://probation-supervision-appointments-api-preprod.hmpps.service.justice.gov.uk'
    ARNS_ASSESSMENT_PLATFORM_API_URL: 'https://arns-assessment-platform-api-preprod.hmpps.service.justice.gov.uk'
    PROBATION_FRONTEND_COMPONENTS_API_URL: 'https://probation-frontend-components-preprod.hmpps.service.justice.gov.uk'
    PROBATION_FRONTEND_COMPONENTS_CONNECT_SRC: 'https://probation-frontend-components-preprod.hmpps.service.justice.gov.uk'
    PROBATION_FRONTEND_COMPONENTS_FONT_SRC: 'https://probation-frontend-components-preprod.hmpps.service.justice.gov.uk'
    FLIPT_URL: 'https://feature-flags-manage-people-on-probation-preprod.hmpps.service.justice.gov.uk'
    INTERVENTIONS_LINK: 'https://hmpps-interventions-ui-preprod.apps.live-1.cloud-platform.service.justice.gov.uk'
    SUPERVISION_CONTACTS_LINK: 'https://probation-supervision-contacts-ui-preprod.hmpps.service.justice.gov.uk'
    DELIUS_LINK: 'https://ndelius.pre-prod.delius.probation.hmpps.dsd.io'
    OASYS_LINK: 'https://pp-int.oasys.service.justice.gov.uk'
    RECALL_LINK: 'https://consider-a-recall-preprod.hmpps.service.justice.gov.uk/'
    CAS1_LINK: 'https://approved-premises-preprod.hmpps.service.justice.gov.uk/'
    CAS3_LINK: 'https://transitional-accommodation-preprod.hmpps.service.justice.gov.uk/referrals'
    CAVAL_LINK: 'https://create-and-vary-a-licence-preprod.hmpps.service.justice.gov.uk'
    EPF2_LINK: '/'
    TIER_LINK: 'https://tier-preprod.hmpps.service.justice.gov.uk/case'
    SENTENCE_PLAN_LINK: 'https://sentence-plan-preprod.hmpps.service.justice.gov.uk'
    SENTENCE_PLAN_LINK_V2: 'https://arns-assessment-platform-preprod.hmpps.service.justice.gov.uk/access/sentence-plan/crn'
    E_SUPERVISION_API_URL: 'https://esupervision-api-preprod.hmpps.service.justice.gov.uk'
    EMDI_API_URL: 'https://electronic-monitoring-data-insights-api-preprod.hmpps.service.justice.gov.uk'
    ESUPERVISION_GUIDANCE_LINK: 'https://probation-check-in-preprod.hmpps.service.justice.gov.uk'
    CHAR_COUNT: 12000
    ENVIRONMENT_NAME: PRE-PRODUCTION
    ENVIRONMENT: preprod

  scheduledDowntime:
    enabled: true

generic-prometheus-alerts:
  alertSeverity: manage-people-on-probation-preprod
