const outcomeLabelMap = new Map<string, string>(
  [
    ['acceptable - alcohol consumption no breach', 'Acceptable - Alcohol consumption but no breach'],
    ['acceptable - monitoring only', 'Acceptable - Monitoring only'],
    ['unacceptable alcohol consumption', 'Unacceptable alcohol consumption'],
    ['risk review', 'Risk review'],
    ['contact frequency', 'Contact frequency'],
    ['oasys/assessment', 'OASys/Assessment'],
    ['other - see notes', 'Other - see notes'],
    ['referral/other agency contact', 'Referral or other agency contact'],
    ['significant event', 'Significant event'],
    ['acceptable - critical communications - no breach', 'Acceptable critical communications - no breach'],
    ['unacceptable critical communications', 'Unacceptable critical communications'],
    ['alcohol poisoning', 'Alcohol poisoning'],
    ['awaiting further information', 'Awaiting further information'],
    ["coroner's conclusion of: cause unascertained", "Coroner's conclusion - cause unascertained"],
    ['drug poisoning: intent undetermined', 'Drug poisoning - intent unknown'],
    ['drug poisoning: intentional', 'Drug poisoning - intentional'],
    ['drug poisoning: unintentional', 'Drug poisoning - unintentional'],
    ['fall from height: intent undetermined', 'Fall from height - intent unknown'],
    ['fall from height: intentional', 'Fall from height - intentional'],
    ['fall from height: unintentional', 'Fall from height - unintentional'],
    ['homicide: other', 'Homicide - other'],
    ['homicide: shooting', 'Homicide - shooting'],
    ['homicide: stabbing', 'Homicide - stabbing'],
    ['natural causes: cancer related', 'Natural causes - cancer related'],
    ['natural causes: heart related', 'Natural causes - heart related'],
    ['natural causes: other', 'Natural causes - other'],
    ['non-natural: accident / other', 'Unnatural - accident or other'],
    ['non-natural: road traffic accident', 'Unnatural - road traffic accident'],
    ['self-inflicted: hanging', 'Self-inflicted - hanging'],
    ['self-inflicted: other', 'Self-inflicted - other'],
    ['disclosure not required', 'Disclosure not required'],
    ["liaison with children's services", "Liaison with children's services"],
    ['mappa - other', 'MAPPA - other'],
    ['mappa / probation disclosure: child sex offences', 'MAPPA or probation disclosure - child sex offences'],
    ['other (provide detail in notes)', 'Other (provide detail in notes)'],
    ['referral to dvds', 'Referral to DVDS'],
    ['referral to marac for further information sharing', 'Referral to MARAC for further information sharing'],
    ['disclosure completed (other)', 'Other disclosure completed'],
    ['disclosure refused (other)', 'Other disclosure refused'],
    ['dvds disclosure complete', 'DVDS disclosure complete'],
    ['dvds referral refused', 'DVDS referral refused'],
    ['referral decision - accepted', 'Referral decision - accepted'],
    ['referral decision - pending', 'Referral decision - pending'],
    ['rejected - remain at level 1', 'Rejected - remain at level 1'],
    ['community amber-rag progression review', 'Community - amber RAG progression review'],
    ['consideration of licence termination', 'Consideration of terminating licence'],
    ['consideration of recall', 'Consideration of recall'],
    ['consideration of reducing supervision frequency', 'Consideration of reducing supervision frequency'],
    ['consideration of supervision reimposition', 'Consideration of reimposing supervision'],
    ['consideration of supervision suspension', 'Consideration of suspending supervision'],
    ['escalation of risk in community', 'Escalation of risk in community'],
    ['following negative parole outcome', 'Following a negative parole outcome'],
    ['following recall', 'Following recall'],
    ['following recategorisation', 'Following recategorisation'],
    ['following remission from secure hospital', 'Following remission from secure hospital'],
    ['initial panel following release', 'Initial panel following release'],
    ['panel not held', 'Panel not held'],
    ['prison amber-rag progression review', 'Prison - amber RAG progression review'],
    ['prison red-rag progression review', 'Prison - red RAG progression review'],
    ['delay of home visit', 'Home visit delayed'],
    ['follow-up action required', 'Follow-up action required'],
    ['follow-up action completed', 'Follow-up action completed'],
    ['home visit not undertaken', 'Home visit not carried out'],
    ['management oversight decision', 'Management oversight decision'],
    ['pp recommendation endorsed', 'Probation practitioner recommendation endorsed'],
    ['home visit - referred for spo decision', 'Home visit - referred for SPO decision'],
    ['home visit approved', 'Home visit approved'],
    ['home visit exempted', 'Home visit exempted'],
    ['home visit not approved', 'Home visit not approved'],
    ['review complete - refer to level 2 - spo endorsed', 'Review complete - refer to Level 2 (SPO endorsed)'],
    ['review complete - refer to level 3 - spo endorsed', 'Review complete - refer to Level 3 (SPO endorsed)'],
    [
      'review complete - retain at level 1 - mo not required',
      'Review complete - retain at Level 1 (management oversight not required)',
    ],
    ['review complete - retain at level 1 - spo endorsed', 'Review complete - retain at Level 1 (SPO endorsed)'],
    ['accepted - level 2', 'Accepted - level 2'],
    ['accepted - level 3', 'Accepted - level 3'],
    ['category 3 referral rejected - not mappa managed', 'Category 3 referral rejected - not MAPPA managed'],
    ['domestic abuse', 'Domestic abuse'],
    ['domestic abuse and other check', 'Domestic abuse and other check'],
    ['other check (not da)', 'Other check (not domestic abuse)'],
    ['request not sent - up to date information already', 'Request not sent - up to date information already'],
    ['enforcement action consideration', 'Enforcement action consideration'],
    ['reviewed assessment frequency', 'Reviewed assessment frequency'],
    ['reviewed attendance frequency', 'Reviewed attendance frequency'],
    ['recommendation declined', 'Recommendation declined'],
    ['recommendation endorsed', 'Recommendation endorsed'],
    ['response received - known to social services', 'Response received - known to social services'],
    ['response received - not known to social services', 'Response received - not known to social services'],
    ["enquiry sent to local authority children's service", "Enquiry sent to local authority children's service"],
  ].map(([key, value]) => [key.toLowerCase(), value]),
)

export function toOutcomeLabel(value: string): string {
  if (!value) return value
  return outcomeLabelMap.get(value.toLowerCase()) ?? value
}
