let startOfTodayLocal = startofday(datetime_utc_to_local(now(), "Europe/London"));
let startOfYesterdayLocal = startOfTodayLocal - 1d;
let startOfYesterdayUtc = datetime_local_to_utc(startOfYesterdayLocal, "Europe/London");
let startOfTodayUtc = datetime_local_to_utc(startOfTodayLocal, "Europe/London");
pageViews
| where timestamp >= startOfYesterdayUtc and timestamp < startOfTodayUtc
| where cloud_RoleName == "hmpps-manage-people-on-probation-ui"
| where name == "Sorry, there is a problem with the service - Manage people on probation"
| summarize ["Times shown"] = count()

