name: Generate and Scan with Veracode Pipeline Scan

on:
  workflow_call:

jobs:
  veracode_scan:
    name: Generate and Scan with Veracode Pipeline Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Package build output
        run: |
          mkdir -p veracode-package
          rsync -av --exclude 'veracode-package' ./ veracode-package/
          cd veracode-package
          zip -r ../veracode-artifact.zip .
        shell: bash

      - name: Download Veracode Pipeline Scan
        run: |
          curl -LO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -o pipeline-scan-LATEST.zip
        shell: bash

      - name: Run Veracode Pipeline Scan
        run: |
          java -jar pipeline-scan.jar \
            -vid ${{ secrets.VERACODE_API_ID }} \
            -vkey ${{ secrets.VERACODE_API_KEY }} \
            -f veracode-artifact.zip \
            --appname hmpps-manage-people-on-probation \
            --createprofile true \
            --fail_on_severity=VeryHigh
        shell: bash
