name: E2E Tests

on:
  workflow_call:
    inputs:
      node_version_file:
        description: "Path to Node version file"
        required: false
        type: string
        default: ".nvmrc"

permissions:
  contents: read

jobs:
  e2e_form_tests:
    name: Run Cypress form submit & replay tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.node_version_file }}

      - name: Restore cache
        id: restore-cache
        uses: actions/cache/restore@v4
        env:
          cache-name: node-modules
        with:
          path: |
            ./node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: npm_build_artifacts
          path: |
            build/
            dist/
            assets/stylesheets/

      #####################################################
      ## First Phase: Run app with feature env + form flow
      #####################################################

      - name: Start backend for capturing the request
        shell: bash
        run: |
          npm run start-feature &
          sleep 10
        env:
          NODE_ENV: test

      - name: Run Cypress test: save-request
        run: npx cypress run --spec "integration_tests/e2e/appointments/save-request.cy.ts"

      - name: Kill server (after form test)
        run: |
          pkill -f "node.*server.js" || true

      ####################################################
      ## Second Phase: Run app with standard env + replay
      ####################################################

      - name: Start backend for posting request to api
        shell: bash
        run: |
          npm run start &
          sleep 10
        env:
          NODE_ENV: test

      - name: Run Cypress test: post-appointment
        run: npx cypress run --spec "integration_tests/e2e/appointments/post-appointment.cy.ts"

      - name: Kill server (after replay test)
        run: |
          pkill -f "node.*server.js" || true

      - name: Upload Cypress artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos

      - name: Fail if any Cypress test failed
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('E2E form submit or replay test failed')