name: Security veracode policy scan
on:
  workflow_dispatch:
  schedule:
    - cron: "19 05 * * 1" # Every Monday

jobs:
  security-veracode-policy-check:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security veracode policy scan
    uses: ./.github/workflows/policy_scan.yml
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
