name: Veracode Static Analysis Scan

on:
  workflow_call:
    secrets:
      VERACODE_API_ID:
        required: true
      VERACODE_API_KEY:
        required: true

jobs:
  veracode_static_scan:
    name: Upload and Scan with Veracode Static Analysis
    runs-on: ubuntu-latest

    concurrency:
    group: veracode-scan-hmpps-manage-people-on-probation
    cancel-in-progress: false

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Package build output
        run: |
          mkdir -p veracode-package
          rsync -av --exclude 'veracode-package' ./ veracode-package/
          cd veracode-package
          zip -r ../veracode-artifact.zip .
        shell: bash

      - name: Upload and Scan with Veracode Static Analysis
        uses: veracode/veracode-uploadandscan-action@0.2.7
        with:
          appname: hmpps-manage-people-on-probation
          createprofile: true
          filepath: veracode-artifact.zip
          version: ${{ github.run_number }}
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
